name: learn-github-actions
on:
  push:
    paths:
      - 'drools-docs/**/**.adoc'
      - '.github/workflows/run.yaml'

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - run: |
          bash -c "if [ -n \"$(docker images -f dangling=true -q)\" ]; then docker rmi $(docker images -f dangling=true -q); else echo 'No dangling images to remove.'; fi"
