name: learn-github-actions
on:
  push:
    paths:
      - 'drools-docs/**/**.adoc'
      - '.github/workflows/run.yaml'

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - run: |
          docker image prune -f
